# The compose workflow is provided as a way to run VPP's dependencies without
# needing to install them globally. However, Kafka has problems around running
# inside Docker (memory requirements while running inside a boot2docker VM,
# etc) that may make naive containers untenable in the long run. Once Docker
# has been allocated enough system resources, this compose workflow should
# mitigate most of the problems relating to persistent storage and service
# availability.
#
# Start up:
# `docker-compose up -d`

version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my_root_token
    ports:
      - 8200:8200

volumes:
  postgres-data:
